japan:
  currency: YEN
  country: JAPAN
  rate:
    robbery: 0.01
    medical: 0.015

brazil:
  currency: REAL
  country: BRAZIL
  rate:
    robbery: 0.05
    medical: 0.03

logging:
  level:
    root: WARN
    com.javaacademy.insurance: info

spring:
  output:
  ansi:
    enabled: DETECT