app:
  currency: YEN
  country: JAPAN
  rate:
    robbery: 0.01
    medical: 0.015

logging:
  level:
    root: ERROR
    com.javaacademy.insurance: INFO

spring:
  output:
  ansi:
    enabled: DETECT